name: Scan for secrets
on: [pull_request, push, workflow_dispatch]
jobs:

  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install detect-secrets
        run: |
          pip install detect-secrets
      - name: Run detect-secrets
        run: |          
          detect-secrets scan --all-files --force-use-all-plugins --exclude-files '.git/.*'  > detect-secrets.json
      - name: Analyze detect-secrets
        run: |
          dsjson=$(cat detect-secrets.json)
          echo "${dsjson}"

          count=$(echo "${dsjson}" | jq -c -r '.results | length')

          if [ $count -gt 0 ]; then
            echo "Secrets were detected in code. ${count} file(s) affected. 😵‍💫"
            exit 1
          else
            echo "No secrets were detected in code 🥳"
            exit 0
          fi

  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install TruffleHog
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
          trufflehog --version

      - name: Run TruffleHog
        run: trufflehog filesystem . --exclude-paths '.git/' --fail
  
  gitguardian:  
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - name: GitGuardian scan
        uses: GitGuardian/ggshield/actions/secret@main
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
