name: gitleaks
on: [pull_request, push, workflow_dispatch]
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.

  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install TruffleHog
        run: pip3 install trufflehog
      - name: Run TruffleHog
        run: trufflehog filesystem . --json > /tmp/trufflehog.json

      - name: Upload the scan output
        uses: actions/upload-artifact@v2
        with:
          name: scan_results
          path: /tmp/trufflehog.json
          retention-days: 2
